# Limpieza avanzada del texto
Este notebook aplica una limpieza robusta al texto para eliminar símbolos extraños, emojis, y otros caracteres no deseados antes de la vectorización.

In [1]:
import pandas as pd
import re

# Cargar el dataset
df = pd.read_csv("Tweets.csv")  # Cambia si es necesario
df.head()

,textID,text,selected_text,sentiment
0,cb774db0d1,"I`d have responded, if I were going","I`d have responded, if I were going",neutral
1,549e992a42,Sooo SAD I will miss you here in San Diego!!!,Sooo SAD,negative
2,088c60f138,my boss is bullying me...,bullying me,negative
3,9642c003ef,what interview! leave me alone,leave me alone,negative
4,358bd9e861,"Sons of ****, why couldn`t they put them on t...","Sons of ****,",negative

In [2]:
# Función de limpieza
def limpiar_texto(texto):
    if pd.isna(texto):
        return ""
    texto = texto.lower()
    texto = re.sub(r"http\S+", "", texto)
    texto = re.sub(r"[^a-zA-Z0-9\s]", "", texto)
    texto = re.sub(r"\s+", " ", texto).strip()
    return texto

In [3]:
# Aplicar limpieza a la columna de texto
df["text_limpio"] = df["text"].apply(limpiar_texto)
df[["text", "text_limpio"]].head()

,text,text_limpio
0,"I`d have responded, if I were going",id have responded if i were going
1,Sooo SAD I will miss you here in San Diego!!!,sooo sad i will miss you here in san diego
2,my boss is bullying me...,my boss is bullying me
3,what interview! leave me alone,what interview leave me alone
4,"Sons of ****, why couldn`t they put them on t...",sons of why couldnt they put them on the relea...

In [4]:
# Guardar resultado
df.to_csv("01tweetsLimpios.csv", index=False)
print("✅ Limpieza completa. Archivo guardado como 01tweetsLimpios.csv")
df.head(10)

✅ Limpieza completa. Archivo guardado como 01tweetsLimpios.csv

,textID,text,selected_text,sentiment,text_limpio
0,cb774db0d1,"I`d have responded, if I were going","I`d have responded, if I were going",neutral,id have responded if i were going
1,549e992a42,Sooo SAD I will miss you here in San Diego!!!,Sooo SAD,negative,sooo sad i will miss you here in san diego
2,088c60f138,my boss is bullying me...,bullying me,negative,my boss is bullying me
3,9642c003ef,what interview! leave me alone,leave me alone,negative,what interview leave me alone
4,358bd9e861,"Sons of ****, why couldn`t they put them on t...","Sons of ****,",negative,sons of why couldnt they put them on the relea...
5,28b57f3990,http://www.dothebouncy.com/smf - some shameles...,http://www.dothebouncy.com/smf - some shameles...,neutral,some shameless plugging for the best rangers f...
6,6e0c6d75b1,2am feedings for the baby are fun when he is a...,fun,positive,2am feedings for the baby are fun when he is a...
7,50e14c0bb8,Soooo high,Soooo high,neutral,soooo high
8,e050245fbd,Both of you,Both of you,neutral,both of you
9,fc2cbefa9d,Journey!? Wow... u just became cooler. hehe....,Wow... u just became cooler.,positive,journey wow u just became cooler hehe is that ...